name: 'Hello World'
branding:
  icon: 'message-circle'
  color: 'blue'
description: 'Greet someone and record the time'
inputs:
  who-to-greet: # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  GITHUB_TOKEN:
    description: 'Your GitHub token'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: 'dist/index.js'